"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 10:51:32.790393
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('sku', name=op.f('uq_items_sku'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('barcodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_barcodes_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barcodes')),
    sa.UniqueConstraint('code', name=op.f('uq_barcodes_code'))
    )
    op.create_index(op.f('ix_barcodes_item_id'), 'barcodes', ['item_id'], unique=False)
    op.create_index(op.f('ix_barcodes_status'), 'barcodes', ['status'], unique=False)
    op.create_table('collection_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('session_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], name=op.f('fk_collection_sessions_closed_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_collection_sessions_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_sessions'))
    )
    op.create_index(op.f('ix_collection_sessions_status'), 'collection_sessions', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_operator_id', sa.Uuid(), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('pending_scans', sa.Integer(), nullable=True),
    sa.Column('clock_skew_seconds', sa.Integer(), nullable=True),
    sa.Column('sync_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('duplicate_window_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_operator_id'], ['users.id'], name=op.f('fk_devices_last_operator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_scan_id', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('requested_session_id', sa.String(length=64), nullable=True),
    sa.Column('barcode_id', sa.Uuid(), nullable=False),
    sa.Column('raw_barcode', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('scanned_at_device', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_server', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('sync_state', sa.String(length=30), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['barcode_id'], ['barcodes.id'], name=op.f('fk_scans_barcode_id_barcodes')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_scans_device_id_devices')),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_scans_operator_id_users')),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_scans_resolved_by_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['collection_sessions.id'], name=op.f('fk_scans_session_id_collection_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans')),
    sa.UniqueConstraint('client_scan_id', name=op.f('uq_scans_client_scan_id'))
    )
    op.create_index('ix_scans_dup_lookup', 'scans', ['device_id', 'barcode_id', 'scanned_at_device'], unique=False)
    op.create_index('ix_scans_received', 'scans', ['received_at_server'], unique=False)
    op.create_index('ix_scans_session', 'scans', ['session_id', 'received_at_server'], unique=False)
    op.create_index('ix_scans_sync_state', 'scans', ['sync_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scans_sync_state', table_name='scans')
    op.drop_index('ix_scans_session', table_name='scans')
    op.drop_index('ix_scans_received', table_name='scans')
    op.drop_index('ix_scans_dup_lookup', table_name='scans')
    op.drop_table('scans')
    op.drop_table('devices')
    op.drop_index(op.f('ix_collection_sessions_status'), table_name='collection_sessions')
    op.drop_table('collection_sessions')
    op.drop_index(op.f('ix_barcodes_status'), table_name='barcodes')
    op.drop_index(op.f('ix_barcodes_item_id'), table_name='barcodes')
    op.drop_table('barcodes')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
