"""software releases

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 10:02:54.683618
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('download_url', sa.String(length=1000), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_software_releases')),
    sa.UniqueConstraint('platform', 'version', name='uq_software_releases_platform_version')
    )
    op.create_index('uq_software_releases_active_platform', 'software_releases', ['platform'], unique=True, postgresql_where=sa.text('active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_software_releases_active_platform', table_name='software_releases', postgresql_where=sa.text('active'))
    op.drop_table('software_releases')
    # ### end Alembic commands ###
