"""load programmings

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 11:36:49.365259
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_programmings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], name=op.f('fk_load_programmings_closed_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_load_programmings_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_programmings'))
    )
    op.create_index(op.f('ix_load_programmings_scheduled_date'), 'load_programmings', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_load_programmings_status'), 'load_programmings', ['status'], unique=False)
    op.add_column('loads', sa.Column('programming_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_loads_programming_id'), 'loads', ['programming_id'], unique=False)
    op.create_foreign_key(op.f('fk_loads_programming_id_load_programmings'), 'loads', 'load_programmings', ['programming_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_loads_programming_id_load_programmings'), 'loads', type_='foreignkey')
    op.drop_index(op.f('ix_loads_programming_id'), table_name='loads')
    op.drop_column('loads', 'programming_id')
    op.drop_index(op.f('ix_load_programmings_status'), table_name='load_programmings')
    op.drop_index(op.f('ix_load_programmings_scheduled_date'), table_name='load_programmings')
    op.drop_table('load_programmings')
    # ### end Alembic commands ###
